### ISSUE TITLE
Add Links for Identifiers in Details Panel 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#10]
Primarily the Details section will be linked to other websites. Each identifier is a namepace:id. The links for each namespace can be found here: 

https://github.com/clulab/reach/blob/afff6776cf2449c6de1c16c79776a499e1f06dc6/main/src/main/scala/org/clulab/reach/grounding/ReachIMKBLookups.scala

Example: 

http://identifiers.org/uniprot/P55851

**Comment by RohitChattopadhyay** [comment]
@cannin In the file you linked to, for namespace **be** , baseURL is a GitHub repository ([Ref]( https://github.com/clulab/reach/blob/afff6776cf2449c6de1c16c79776a499e1f06dc6/main/src/main/scala/org/clulab/reach/grounding/ReachIMKBLookups.scala#L143 ) )
Also, the baseURL is permanently redirected.
So should I use the URL of the new repository?

**Comment by cannin** [comment]
For taxonomy, use: http://identifiers.org/taxonomy/ID, example: http://identifiers.org/taxonomy/9606

**Comment by cannin** [comment]
> @cannin In the file you linked to, for namespace **be** , baseURL is a GitHub repository ([Ref](https://github.com/clulab/reach/blob/afff6776cf2449c6de1c16c79776a499e1f06dc6/main/src/main/scala/org/clulab/reach/grounding/ReachIMKBLookups.scala#L143) )
> Also, the baseURL is permanently redirected.
> So should I use the URL of the new repository?

Yes, use: https://github.com/sorgerlab/famplex

**Comment by cannin** [comment]
@RohitChattopadhyay can you underline the identifiers that have links?

**Comment by RohitChattopadhyay** [comment]
> @RohitChattopadhyay can you underline the identifiers that have links?

![image](https://user-images.githubusercontent.com/19877300/59768074-4e35c180-92c1-11e9-84e6-d92f21a91652.png)
Requesting feedback

**Comment by cannin** [comment]
I needed to put more detail. No not that link (remove the CHEBI underline). Links in the sentences the words in red and blue.

**Comment by RohitChattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/19877300/59774574-4bd96480-92cd-11e9-80f9-c3808fa7742d.png)
Added colums mentioned in #39 
Requesting feedback

**Comment by RohitChattopadhyay** [comment]
BaseUrls are set in file [components/identifierDetails.js#L13](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/identifierDetails.js#L13)
Identifier link is done in file [components/identierDetails.js#L38](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/identifierDetails.js#L38)
