### ISSUE TITLE
Setup MongoDB on Mongo Atlas 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#13]
Try to set up the database on Atlas: https://www.mongodb.com/cloud/atlas using your backup files

## Settings: 
* us-east-1
* 512 memory

**Comment by RohitChattopadhyay** [comment]
I tested to import the dumped dataset, for the small dataset I was successful, but as expected it failed for the complete dataset ( quota exceed ).
![image](https://user-images.githubusercontent.com/19877300/58564936-82cad600-824b-11e9-8247-7f15553caf38.png)

I used this command in terminal to perform the import
`mongorestore --host <CONNECTION>.mongodb.net:27017 --ssl --username <USERNAME> --password <PASSWORD> --authenticationDatabase admin`
This command is available in Atlas.
