### ISSUE TITLE
Add react-helmet and react-ga to Gatsby

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#14]
Include and setup react-helmet and react-ga into the site. The exact text is not so important 
 right now, and we'll fix the GA site ID later.

**Comment by RohitChattopadhyay** [comment]
Is using **react-ga** compulsory?
There is a GatsbyJS plugin for Google Analytics : [**gatsby-plugin-google-analytics**](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics)
Thanks

**Comment by cannin** [comment]
Okay, use "Official Plugin" from Gatsby when available; both GA and Helmet exist.

**Comment by RohitChattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/19877300/61189897-90300880-a6b1-11e9-8f47-87004b6bdee8.png)
Google Analytics has been set up.
Tracking ID can be set [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/d68b5782905b305749dd470e27ead352d7f7f6bd/src/gatsby-config.js#L16)
