### ISSUE TITLE
Documenting GraphQL API 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#16]
Can you make a separate graphql document for the API and start documenting it? Example below: 

https://github.com/artsy/metaphysics/blob/1dfa62f91780bab8843755e2081393ba41a59e7f/_schema.graphql

I learned that the "#" commented strings become documentation (screenshot) using the Docs link in the upper right corner. Jus put placeholders for now. We will fill in more text later. 

<img width="1392" alt="Screen Shot 2019-05-30 at 9 55 48 AM" src="https://user-images.githubusercontent.com/790284/58637968-ab8db280-82c1-11e9-99f4-fb850061f5d0.png">

**Comment by cannin** [comment]
Also, in related README. Write instructions for call the GraphQL API using curl: 

https://blog.apollographql.com/4-simple-ways-to-call-a-graphql-api-a6807bcdb355

**Comment by RohitChattopadhyay** [comment]
> Can you make a separate graphql document for the API and start documenting it? Example below:
> 
> https://github.com/artsy/metaphysics/blob/1dfa62f91780bab8843755e2081393ba41a59e7f/_schema.graphql
> 
> I learned that the "#" commented strings become documentation (screenshot) using the Docs link in the upper right corner. Jus put placeholders for now. We will fill in more text later.
> 
> <img alt="Screen Shot 2019-05-30 at 9 55 48 AM" width="1392" src="https://user-images.githubusercontent.com/790284/58637968-ab8db280-82c1-11e9-99f4-fb850061f5d0.png">

The newer version of graphql npm package supports string literals for providing descriptions.([Ref](https://graphql.github.io/graphql-spec/June2018/#sec-Descriptions))

**Comment by cannin** [comment]
String literals are fine. Can you post a screenshot of our GraphiQL here with the Docs tab open as verification that the documentation is working as expected?

**Comment by RohitChattopadhyay** [comment]
Description of queries
![image](https://user-images.githubusercontent.com/19877300/58701808-98faa280-83c1-11e9-8758-c47cf15e4faa.png)

Description for document field ( *participant_b* )
![image](https://user-images.githubusercontent.com/19877300/58701847-bf204280-83c1-11e9-9817-825ced1d1537.png)

**Comment by cannin** [comment]
We need to improve the documentation: 

1. Provide examples of input parameters for every query argument: 

```
articlesByIdentifier(id: String!): Entities
Returns all the articles of the specified identifier (example: ???)
```

2. Update the default graphiQL text: https://github.com/graphql/express-graphql/issues/447 Append to the existing text the example of a REACH file and an example query like your figures above.

**Comment by cannin** [comment]
If an ID is meant as a pmc_id please make the argument "pmc_id" otherwise it is confusing. 

<img width="334" alt="Screen Shot 2019-06-13 at 12 14 21 PM" src="https://user-images.githubusercontent.com/790284/59449312-d1907800-8dd4-11e9-838c-7bd662dc4a8e.png">

and why is article(id: ID!) id: ID and in other places a String? We should aim for consistency.

**Comment by RohitChattopadhyay** [comment]
> If an ID is meant as a pmc_id please make the argument "pmc_id" otherwise it is confusing.
> 
> <img alt="Screen Shot 2019-06-13 at 12 14 21 PM" width="334" src="https://user-images.githubusercontent.com/790284/59449312-d1907800-8dd4-11e9-838c-7bd662dc4a8e.png">
> 
> and why is article(id: ID!) id: ID and in other places a String? We should aim for consistency.

Thanks, I will make the changes and let you know.

In *id : ID!* , ID refers to MongoDB ID  which is of type ObjectId, 
Although it takes a string as an argument.

**Comment by cannin** [comment]
I see. We will have agreed on nomenclature and it might change with time. 

* A "document" is should be an individual record in MongoDB so maybe do document(id: ID!) returns a Document
* An "article" is defined by the pmc_id and it will have 1+  documents associated with it

Also, ignore what I said about changing "id" to pmc_id because in the future not all article IDs will be pmc_ids 

Also, it does not seem like I can do this: identifier(id: "chebi:CHEBI:15356"). What is a "String!"

**Comment by RohitChattopadhyay** [comment]
>Also, it does not seem like I can do this: identifier(id: "chebi:CHEBI:15356").

This has been resolved, there was an error due change of *identifier* to *iden* in the database.
![image](https://user-images.githubusercontent.com/19877300/59456755-ae95b080-8e34-11e9-8b1b-f61c12c5d7a4.png)

Regarding *String!*
**String** represents the type and **!** means that it is a required parameter

**Comment by cannin** [comment]
Documentation for the API is here: https://github.com/RohitChattopadhyay/ihop-reach/blob/docker-api/src/schema.graphql

**Comment by RohitChattopadhyay** [comment]
> 1. Update the default graphiQL text: [graphql/express-graphql#447](https://github.com/graphql/express-graphql/issues/447) Append to the existing text the example of a REACH file and an example query like your figures above.

Welcome Message is set [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/4fd891916f996570c39fabaa12d6bafbe48d210f/src/graphiql/src/App.js#L39)
