### ISSUE TITLE
Get MongoDB Database Statistics 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#18]
Can you answer the following questions from using the database? Try to do this with MongoDB queries. Record the queries you use. Alternatively, use Python.

* How many entries have "hypothesis_information" as true? 
* How many entries have "negative_information" as true? 
* What is the counts of unique identifiers per namespace? Example: How many unique uniprot IDs exist? How many interpro? ... 
* What are the counts for unique taxonomy? Example: How many taxonomy:9606 exist? 
* How many "evidence" have less than 50 characters? How many have less than 25? 
* What is the total number of documents?
* How many unique pmc_ids exist? 

Answers to these queries may help us filter down the number of pages that need to be generated.

**Comment by RohitChattopadhyay** [comment]
The Analysis report can be viewed in this [Google Doc](https://docs.google.com/document/d/148H0S0h2VewO3-aQbbKHZr7q9A6Yi7lCbVVGiThv6Xg/edit?usp=sharing)

**Comment by cannin** [comment]
Can you and another entry? Can you count the number interactions by type? 

       "interaction_type" : "adds_modification",

**Comment by RohitChattopadhyay** [comment]
Added Interaction type in the Analysis Report [Google Doc file](https://docs.google.com/document/d/148H0S0h2VewO3-aQbbKHZr7q9A6Yi7lCbVVGiThv6Xg/edit). Also added the findings below.

Interaction Type | Count
-- | --
decreases_activity | 643,085
increases_activity | 1,248,910
inhibits_modification | 42,503
adds_modification | 858,847
binds | 680,707
translocates | 15,272

**Comment by cannin** [comment]
@RohitChattopadhyay This table is good. Can you make a separate table (or JSON document) just like this, but with one more column/field (count the number of synonyms). 

https://gist.github.com/RohitChattopadhyay/2606f58d8031ef5565707fec828f57d8

There are some obvious errors from NLP (not your code). Some entries like uniprot:P07659 have 2000 synonyms this is not correct.

**Comment by RohitChattopadhyay** [comment]
> @RohitChattopadhyay This table is good. Can you make a separate table (or JSON document) just like this, but with one more column/field (count the number of synonyms).
> 
> https://gist.github.com/RohitChattopadhyay/2606f58d8031ef5565707fec828f57d8
> 
> There are some obvious errors from NLP (not your code). Some entries like uniprot:P07659 have 2000 synonyms this is not correct.

I have updated the [Google Sheet](https://docs.google.com/spreadsheets/d/1QhIs6YaOojr_dVmCh13gqrME3sWYOBx0quSTiBDLRXw/edit#gid=521642250) with the information you requested.

Thanks
