### ISSUE TITLE
Add Flow for Static Type Checking

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#19]
Add Flow for static type checking: 

https://flow.org/en/
https://www.gatsbyjs.org/packages/gatsby-plugin-flow

**Comment by cannin** [comment]
Can you share an image here confirming Flow is working as part of the Gatsby build?

**Comment by RohitChattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/19877300/58854804-fb9eb780-86bb-11e9-91cd-9746772d9ff1.png)
Is this okay? I am using flow for the first time.

**Comment by cannin** [comment]
Do these help: 

https://stackoverflow.com/questions/51358193/how-do-i-correctly-setup-flow-js-in-a-gatsby-project/51358194#51358194
https://medium.com/@sgpropguide/adding-flow-types-to-gatsbyjs-baeb6bc0c02
