### ISSUE TITLE
Create Docker Container for GraphQL API

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#21]
Same as #5 create a Dockerfile

**Comment by RohitChattopadhyay** [comment]
@cannin , For the database container image, in `docker-compose.yml` should I use our already created database image ([rchattopadhyay/ihop-database](https://cloud.docker.com/repository/docker/rchattopadhyay/ihop-database)) or official mongo image?

**Comment by RohitChattopadhyay** [comment]
> @cannin , For the database container image, in `docker-compose.yml` should I use our already created database image ([rchattopadhyay/ihop-database](https://cloud.docker.com/repository/docker/rchattopadhyay/ihop-database)) or official mongo image?

Successfully tested both of them, both of them are running.

**Comment by RohitChattopadhyay** [comment]
Image in Docker Hub [rchattopadhyay/reach-api](https://hub.docker.com/r/rchattopadhyay/reach-api)
Synced branch for auto-build [RohitChattopadhyay/docker-api](https://github.com/RohitChattopadhyay/ihop-reach/tree/docker-api)
