### ISSUE TITLE
Build Demo Site with Database Subset

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#22]
Create a working demo site with a subset of the database. Maybe grab all the articles associated with 10 identifiers? 

I expect to see URLs like: 

https://laughing-goldstine-daec90.netlify.com/details/SNF1 

with one for each participant identifier.

**Comment by RohitChattopadhyay** [comment]
While testing graphql API , I found `entity_text` like the following:
![image](https://user-images.githubusercontent.com/19877300/58750450-4946d480-84b0-11e9-9a59-546135a4711a.png)
Need guidance regarding handling such entity_text for making the URL

**Comment by cannin** [comment]
Use slugs (https://www.npmjs.com/package/slug) when making URLs.

**Comment by RohitChattopadhyay** [comment]
Log of build process using Database subset can be found [here](https://gist.github.com/RohitChattopadhyay/9bc48e514be23b5192019845229d5760).

**Comment by RohitChattopadhyay** [comment]
> Create a working demo site with a subset of the database. Maybe grab all the articles associated with 10 identifiers?
> 
> I expect to see URLs like:
> 
> https://laughing-goldstine-daec90.netlify.com/details/SNF1
> 
> with one for each participant identifier.

Since we are creating pages by identifier, can the url be made using the identifier instead of entity_text?
Like https://laughing-goldstine-daec90.netlify.com/details/taxonomy:9606 ?
I am finding it difficult to create a mapping between entity_text and identifier due to the large size of the database.

**Comment by cannin** [comment]
Yes, that URL form is okay.

**Comment by RohitChattopadhyay** [comment]
> > Create a working demo site with a subset of the database. Maybe grab all the articles associated with 10 identifiers?
> > I expect to see URLs like:
> > https://laughing-goldstine-daec90.netlify.com/details/SNF1
> > with one for each participant identifier.
> 
> Since we are creating pages by identifier, can the url be made using the identifier instead of entity_text?
> Like https://laughing-goldstine-daec90.netlify.com/details/taxonomy:9606 ?
> I am finding it difficult to create a mapping between entity_text and identifier due to the large size of the database.

For identifiers having 3 components like in chebi:CHEBI:1327
Should I make the url like
 */details/chebi/1327*  (option 1), or
 */details/chebi/CHEBI:1327* (option 2)?

**Comment by cannin** [comment]
Option 2, but only if you intend to do /details/taxonomy/9606 it should be consistent. /details/namespace/id Do not remove content from the IDs even if it seems duplicated.

**Comment by cannin** [comment]
But it would be preferable to leave the colon taxnomy:9606 less code that you write and needs maintenance.

**Comment by cannin** [comment]
Change header to the following:

<img width="635" alt="Screen Shot 2019-06-07 at 8 29 39 AM" src="https://user-images.githubusercontent.com/790284/59104147-c03ffb00-88fe-11e9-9320-6e1f3ef7ddab.png">

**Comment by RohitChattopadhyay** [comment]
@cannin , The demo is deployed at https://ihop-reach.surge.sh 
[List of identifier pages](https://gist.github.com/RohitChattopadhyay/2606f58d8031ef5565707fec828f57d8)

Please note the demo is made using 1000 article subset and the search index is built using complete dataset. So you might get several 404 errors in the search page.
Thanks

**Comment by cannin** [comment]
Make a new gist with the JSON that shows the synonyms and the IDs (from the separate collection you made) for this ID subset. As is it is too hard to guess what I can search for.

**Comment by RohitChattopadhyay** [comment]
> Make a new gist with the JSON that shows the synonyms and the IDs (from the separate collection you made) for this ID subset. As is it is too hard to guess what I can search for.

The list is available [here](https://gist.github.com/RohitChattopadhyay/2606f58d8031ef5565707fec828f57d8#file-13june19-md).
Thanks

**Comment by RohitChattopadhyay** [comment]
[Complete list of identifiers](https://docs.google.com/spreadsheets/d/1QhIs6YaOojr_dVmCh13gqrME3sWYOBx0quSTiBDLRXw/edit#gid=521642250)
