### ISSUE TITLE
Filter Reported Sentences Without Entity Text

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#23]
Reported sentences should have the entity text

**Comment by RohitChattopadhyay** [comment]
@cannin Sentences with length<50 are being filtered out ([code](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/sentenceView.js#L139))
Some sentence has words like, `it they these` as a reference to the Entity, are these sentences okay or needs to be filtered out? Please note that these words are not present in `participant_a/b.entity_text` hence they are not highlighted.
[Example](https://gist.github.com/RohitChattopadhyay/8cfc685d289f57200074e87f086f4df6#file-document-json-L30)
