### ISSUE TITLE
Make Links from Highlighted Entities Other Pages 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#27]
On page /details/uniprot:123 if entity_text EXAMPLE (with identifier: uniprot:234) is highlighted the text EXAMPLE should have a link to page /details/uniprot:234

**Comment by cannin** [comment]
@RohitChattopadhyay Highlight entities but do not link if the identifier is a UAZ identifier since those pages do not exist

**Comment by RohitChattopadhyay** [comment]
> @RohitChattopadhyay Highlight entities but do not link if the identifier is a UAZ identifier since those pages do not exist

Changes made in file [src/sentenceView.js](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/sentenceView.js#L74)
