### ISSUE TITLE
Set a Cookie when a Sentence Content when PMC Link Clicked 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#29]
Please set a cookie. Related to #28

https://www.netlify.com/blog/2017/01/19/setting-cookies-in-react/
https://github.com/reactivestack/cookies/tree/master/packages/react-cookie

name: ihop-reach 
value: {"pmc_id": PMC, "text": SENTENCE}
path: /
expires: 24 hours 
sameSite: true

**Comment by RohitChattopadhyay** [comment]
Any Cookie consent pop up, like for GDPR required?

**Comment by cannin** [comment]
Not for now.

Augustin Luna

**Comment by cannin** [comment]
For the document icon that is clicked can you add a title attribute with the text 

```
<a href=X data-sentence="activation of the promoters of gadd45 (growth arrest and DNA damage-inducible gene 45), gas2">Y</a>
```

**Comment by RohitChattopadhyay** [comment]
Cookie Configuration is set [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/sentenceView.js#L93)
