### ISSUE TITLE
Build Site Mockup Using GatsbyJS

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#3]
A preliminary site mockup needs to be made using GatsbyJS

**Comment by RohitChattopadhyay** [comment]
@cannin , I have made some basic wireframes for home, search and sentence view, requesting your feedback
Wireframes can be found [here](https://docs.google.com/document/d/1yhBGNwYcLxfzteJtYHnzWVgwhSDHDu-K04yKfL4BNOQ/edit#).

**Comment by RohitChattopadhyay** [comment]
@cannin , I have pushed([code](https://github.com/RohitChattopadhyay/ihop-reach/tree/frontend-dev)) the basic screen for [Home](https://laughing-goldstine-daec90.netlify.com/) and [details page](https://laughing-goldstine-daec90.netlify.com/details/), requesting feedback.
The content is hardcoded now. I have not yet implemented Sentence view highlighting.

Need help regarding what content of the article will be shown in the search results page

**Comment by cannin** [comment]
Regarding Details page. For now, we will limit ourselves to the content in the database. Here are some edits:

<img width="1264" alt="Screen Shot 2019-05-31 at 8 15 34 AM" src="https://user-images.githubusercontent.com/790284/58705167-5d89b500-837c-11e9-852a-901e4e82ebd3.png">

<img width="661" alt="Screen Shot 2019-05-31 at 8 17 21 AM" src="https://user-images.githubusercontent.com/790284/58705225-8dd15380-837c-11e9-9922-bc34f78c4b84.png">

**Comment by cannin** [comment]
For each sentence, highlight each trigger and both participant "entity_text"

**Comment by RohitChattopadhyay** [comment]
> For each sentence, highlight each trigger and both participant "entity_text"

In the iHOP site, on hovering the highlighted terms, more details about the term are shown as a popup. Can you please guide me from where these details are being fetched.

**Comment by RohitChattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/19877300/58739555-823b6680-8428-11e9-994c-38ae8f4ef28b.png)
@cannin Requesting your feedback, used random colours for each unique `entity_type`. The colour are to be decided after discussion with you.
2nd evidence is intentionally taken to test the code.
PMC ID URL to be added.
[Example on Surge](https://ihop-reach.surge.sh)
Code available in [forked repository](https://github.com/RohitChattopadhyay/ihop-reach/commit/56a683835df858dcd9b75705af855b1236fe23c5)

**Comment by cannin** [comment]
Closing this for now; I think we have our mockup.

**Comment by RohitChattopadhyay** [comment]
> @cannin Requesting your feedback, used random colours for each unique `entity_type`. The colour are to be decided after discussion with you.

Color is set [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/sentenceView.js#L25)
