### ISSUE TITLE
Make Gatsby Site Links Open in New Tab

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#32]
Use target="_blank" on links

**Comment by cannin** [comment]
Also, do this for the identifier links like UniProt Q9SAG8

**Comment by RohitChattopadhyay** [comment]
Changes made in file [components/sentenceView.js](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/sentenceView.js#L76)
