### ISSUE TITLE
Add Hypothesis Information to Details Panel

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#33]
Add a new column to details table: 

* If "hypothesis_information":false from extracted_information then show icon fa-star  
* If "hypothesis_information":true then show fa-star-half-o

**Comment by RohitChattopadhyay** [comment]
> Add a new column to details table:
> 
> * If "hypothesis_information":false from extracted_information then show icon fa-star
> * If "hypothesis_information":true then show fa-star-half-o

I ran some queries and noticed that `hypothesis_information` is not the same across all documents of the identifier. How should I decide its value?
[Example query](http://reach-api.nrnb-docker.ucsd.edu/?query=query%20detailsByID(%24id%3A%20String!)%20%7B%0A%20%20articlesByIdentifier(id%3A%20%24id)%20%7B%0A%20%20%20%20searchkey%0A%20%20%20%20articles%20%7B%0A%20%20%20%20%20%20pmc_id%0A%20%20%20%20%20%20evidence%0A%20%20%20%20%20%20trigger%0A%20%20%20%20%20%20extracted_information%20%7B%0A%20%20%20%20%20%20%20%20participant_a%20%7B%0A%20%20%20%20%20%20%20%20%20%20entity_text%0A%20%20%20%20%20%20%20%20%20%20entity_type%0A%20%20%20%20%20%20%20%20%20%20identifier%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20participant_b%20%7B%0A%20%20%20%20%20%20%20%20%20%20entity_text%0A%20%20%20%20%20%20%20%20%20%20entity_type%0A%20%20%20%20%20%20%20%20%20%20identifier%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20hypothesis_information%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22id%22%3A%20%22chebi%3ACHEBI%3A16865%22%0A%7D&operationName=detailsByID)

**Comment by cannin** [comment]
This is per sentence (NOT one per page) in the sentence table. 

[query](http://reach-api.nrnb-docker.ucsd.edu/?query=query%20detailsByID(%24id%3A%20String!)%20%7B%0A%20%20articlesByIdentifier(id%3A%20%24id)%20%7B%0A%20%20%20%20articles%20%7B%0A%20%20%20%20%20%20pmc_id%0A%20%20%20%20%20%20extracted_information%20%7B%0A%20%20%20%20%20%20%20%20hypothesis_information%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22id%22%3A%20%22chebi%3ACHEBI%3A16865%22%0A%7D&operationName=detailsByID)

if "hypothesis_information" is not true or false let me know

**Comment by cannin** [comment]
Can you put the hypothesis icon in a separate <td>? Otherwise, the two icons sometimes wrap.

**Comment by RohitChattopadhyay** [comment]
Relevant Code available [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/sentenceView.js#L238)
