### ISSUE TITLE
Make Details Panel Table Filterable

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#35]
Allow users to filter (e.g., half-star/full star)/search (e.g., sentences) the table. 

![filter-ui](https://user-images.githubusercontent.com/790284/59518711-3f4fa900-8e94-11e9-81b1-d85933a227f3.png)

**Comment by RohitChattopadhyay** [comment]
I searched a bit and found [list.js](https://www.npmjs.com/package/list.js) satisfies our needs.
Requesting your views.
Thanks

**Comment by cannin** [comment]
What about this (it is much more widely used):
 https://www.npmjs.com/package/react-table

**Comment by RohitChattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/19877300/59967648-bf3bda00-954a-11e9-8e31-d499b26ab32a.png)

Example Link [Link1](http://ihop-reach.surge.sh/details/uniprot:TS-1313) [Link2](http://ihop-reach.surge.sh/details/uniprot:TS-1001)
[Available pages](https://gist.github.com/RohitChattopadhyay/2606f58d8031ef5565707fec828f57d8#file-22june19-ihop-reach-surge-sh-md)

Requesting feedback @cannin 
Thanks

**Comment by RohitChattopadhyay** [comment]
Filter logic implemented [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/sentenceView.js#L106)
