### ISSUE TITLE
Use Cache API for Search Index

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#38]
Store the search_index on the client machine to avoid re-downloads: https://davidwalsh.name/cache

**Comment by cannin** [comment]
The caching config using the gatsby-offline-plugin is here: 

https://github.com/RohitChattopadhyay/ihop-reach/blob/f9d86c5d30da0ea57f2801fb35714f5fca150636/src/gatsby-config.js#L75

**Comment by RohitChattopadhyay** [comment]
Following is the performance comparision for web app
<hr/>

Before gzip compression
![48%](https://user-images.githubusercontent.com/19877300/60356986-0533ea80-99f0-11e9-9549-fc8aeeedea78.png)
After caching
![91%](https://user-images.githubusercontent.com/19877300/60357035-31e80200-99f0-11e9-8439-5e09b87f209e.png)
Please note this audit was run on 2nd load of the page. 1st load involves the download of search_index.json (6.8MB) hence has poor performance.

**Comment by cannin** [comment]
@RohitChattopadhyay can we close this now that HTTPS has been enabled for the Caching service worker?

**Comment by RohitChattopadhyay** [comment]
> @RohitChattopadhyay can we close this now that HTTPS has been enabled for the Caching service worker?

Thanks, this issue can be closed. It has been tested after implementing SSL #52 . It is working fine, typeahead, as well as search, are working.
