### ISSUE TITLE
Add Additional Columns to Details Panel 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#39]
Column 1: Put fa-minus-circle if negative_information: true 
Column 2: Put fa-male if context taxonomy is 9606

**Comment by RohitChattopadhyay** [comment]
> Column 1: Put fa-minus-circle if negative_information: true
> Column 2: Put fa-male if context taxonomy is 9606

For species column, I have used *Human* for the title tag.
`<i title="Human" className="fa fa-male" />`
Is it okay?

**Comment by cannin** [comment]
That's fine

**Comment by RohitChattopadhyay** [comment]
Columns added in [components/sentenceView.js](https://github.com/RohitChattopadhyay/ihop-reach/blob/9d7c7cb716b5f5e03f36bd68630d101916e97353/src/src/components/sentenceView.js#L252).
