### ISSUE TITLE
Make Swagger Documentation for pyeve REST API 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#4]
Provide Swagger documentation for the API: https://github.com/pyeve/eve-swagger

**Comment by RohitChattopadhyay** [comment]
I have started work on this with the 2 confirmed API endpoints, @cannin  please have a look at
https://app.swaggerhub.com/apis-docs/RohitChattopadhyay/i-hop_reach_api/1.0

**Comment by RohitChattopadhyay** [comment]
@cannin , I have added the identifier endpoint in the [API Documentation](https://app.swaggerhub.com/apis-docs/RohitChattopadhyay/i-hop_reach_api/) 
Requesting you to go through it and provide feedback

**Comment by cannin** [comment]
We will focus on GraphQL
