### ISSUE TITLE
Add Date Column to Site

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#47]
1. Add the PMID dates to the database as a new collection
2. Make a new column in the site with the year (on the left between the human icon and sentence)
3. Re-build the site

**Comment by RohitChattopadhyay** [comment]
> 1. Add the PMID dates to the database as a new collection

The total number of documents is `29,144,667` out of which `4,765,992` have *pmcid* others don't. Even after indexing, the queries are very slow, this will affect Gatsby build and might effect graphql performance ( for relevant queries ).

As a solution, should I remove all the rows which don't have pmcid or year?

**Comment by RohitChattopadhyay** [comment]
> > 1. Add the PMID dates to the database as a new collection
> 
> The total number of documents is `29,144,667` out of which `4,765,992` have _pmcid_ others don't. Even after indexing, the queries are very slow, this will affect Gatsby build and might effect graphql performance ( for relevant queries ).
> 
> As a solution, should I remove all the rows which don't have pmcid or year?

The bottleneck is regex, exact searches are performing better.

**Comment by cannin** [comment]
Yes, it should be an exact match. You can remove the records without PMCID if still too slow.

**Comment by RohitChattopadhyay** [comment]
> Yes, it should be an exact match. You can remove the records without PMCID if still too slow.

It is not much slow for non-regex queries, but the collection size is around 3.5GB, so removing documents which will not be used can reduce the size to 600MB.
Also, due to this, api/mongo container is consuming 9GB RAM in UCSD server

**Comment by RohitChattopadhyay** [comment]
GraphQL Query to get details from PubMed using PMCID is [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/681cf5934240af33a19008443cb6e4bee2aac857/src/index.js#L381) .

**Comment by RohitChattopadhyay** [comment]
> 2. Make a new column in the site with the year (on the left between the human icon and sentence)

Date Column has been added, it can be found [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/e6581e827d50aa7228e4023b9d57bb16f8a046e4/src/src/components/sentenceView.js#L256).

**Comment by RohitChattopadhyay** [comment]
Build successful
Build time: 59 minutes
[Build Log](https://docs.google.com/document/d/1l5IJf-7rWi0QibmtSX5hYACDjJOCdGX_gygYqHA6V80) , [Web Application](http://reach.nrnb-docker.ucsd.edu/)

**Comment by cannin** [comment]
Thanks this is not too slow
