### ISSUE TITLE
Add Additional Animal Information for Taxonomy Column

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#49]
Change the human icon to a two-letter symbol for the following organisms: 

9606: Human -> Hs
10090: Mouse -> Mm 
4932: Yeast -> Sc 
10116: Rat -> Rn

**Comment by RohitChattopadhyay** [comment]
The filter in details view also has been modified accordingly

Build Successful
Build time: 59 minutes
[Build Log](https://docs.google.com/document/d/1l5IJf-7rWi0QibmtSX5hYACDjJOCdGX_gygYqHA6V80/edit?usp=sharing) , [Web Application](http://reach.nrnb-docker.ucsd.edu/)
Related issue #50
