### ISSUE TITLE
Add SSL for enabling HTTPS protocol

### ISSUE THREAD

**Issue by RohitChattopadhyay** [cannin/ihop-reach#52]
SSL Certificate provided by [Lets's Encrypt](https://letsencrypt.org/)
Let's Encrypt handled by [letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) for [nginx-proxy](https://github.com/jwilder/nginx-proxy)

**Comment by RohitChattopadhyay** [comment]
Requests using `http` are being `307` redirected to `https`.

**Comment by cannin** [comment]
@RohitChattopadhyay can we close this?

**Comment by RohitChattopadhyay** [comment]
> @RohitChattopadhyay can we close this?

Thanks
It can be closed, I was waiting for you to test it.
Instructions have already been modified in README files.

**Comment by cannin** [comment]
This is the expected behavior correct? 

<img width="1392" alt="Screen Shot 2019-07-11 at 11 48 25 AM" src="https://user-images.githubusercontent.com/790284/61065525-d8111000-a3d1-11e9-904d-d76ed501a644.png">

**Comment by RohitChattopadhyay** [comment]
No, the console should not give any error, can you please try in incognito or another browser once.
I have tested in Chrome, Firefox in Ubuntu

> This is the expected behavior correct?
> 

> <img alt="Screen Shot 2019-07-11 at 11 48 25 AM" width="1392" src="https://user-images.githubusercontent.com/790284/61065525-d8111000-a3d1-11e9-904d-d76ed501a644.png">
