### ISSUE TITLE
Add Journal Title to Details Column to Site

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#54]
Add a column to the right of the sentence that has the Journal Title you have extracted.

**Comment by RohitChattopadhyay** [comment]
Desktop View
![image](https://user-images.githubusercontent.com/19877300/60926257-9b56f300-a2c3-11e9-94ee-313085475d22.png)
Mobile View
![image](https://user-images.githubusercontent.com/19877300/60926342-ce00eb80-a2c3-11e9-9fb9-62458f2b69f2.png)
Requesting feedback
Thanks

**Comment by cannin** [comment]
This is good I would move the date to the rightmost. And there needs to be
more searches for the dates and journal.

**Comment by RohitChattopadhyay** [comment]
Should I make it _italic_ so that it is easy to distinguish?
![image](https://user-images.githubusercontent.com/19877300/60926754-2c7a9980-a2c5-11e9-874d-3507e66996ea.png)

**Comment by RohitChattopadhyay** [comment]
> This is good I would move the date to the rightmost. And there needs to be more searches for the dates and journal.

I have merged sentences and journal_title into the single search field, is that ok? Should I add Year as well in this field or separate for each? The placeholder message can be changed accordingly
I think it will become clumsy if we add so many fields.

**Comment by cannin** [comment]
It would be best to leave these separate (year, sentence, journal) so they
can be searched separately. I agree that too many columns are bad, but we
haven't arrived at what the "right" columns are, so don't worry too much
about this for now.

**Comment by cannin** [comment]
https://digital.gov/2014/10/28/trends-on-tuesday-8-ways-to-format-tables-for-responsive-web-design/

Options 2, 5, 1 would be my suggestions for mobile view (most to least preferred). If 5 then I would keep: PMC link, hypothesis_information, negative_info, organism, sentence.

**Comment by RohitChattopadhyay** [comment]
> Options 2, 5, 1 would be my suggestions for mobile view (most to least preferred). If 5 then I would keep: PMC link, hypothesis_information, negative_info, organism, sentence.

Taking inspiration from option 2, I have tried the following layout for the small screen device.
![image](https://user-images.githubusercontent.com/19877300/61254282-8fff3e00-a781-11e9-936e-49131b34d117.png)
This can be tested [here](https://ihop-reach.surge.sh/details/chebi:CHEBI:1)
Desktop design is untouched, requesting feedback
Thanks

**Comment by RohitChattopadhyay** [comment]
Option 2 has been deployed, requesting feedback
Link: https://reach.nrnb-docker.ucsd.edu/details/chebi:CHEBI:1

The table filters have been improved to support regex
