### ISSUE TITLE
Allow the GraphQL API to search evidence by regular expression. 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#55]
Potential users suggested that this might be an important feature for them to look for specific words.

**Comment by RohitChattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/19877300/61061592-22b67a80-a41a-11e9-981f-dc0d95e24eb9.png)
Basic search in evidence using the keyword is already available.
Does the user want to send a REGEX as an argument?

**Comment by cannin** [comment]
Could I do "methylation.*mediated" and return just the "CG methylation ..." result from your screenshot? If not, then that's the feature requested. If you believe that this will cause the search to be excessively slow, then split it to a separate parameter like regex (boolean) to switch between the two behaviors.

**Comment by RohitChattopadhyay** [comment]
> Could I do "methylation.*mediated" and return just the "CG methylation ..." result from your screenshot? If not, then that's the feature requested. If you believe that this will cause the search to be excessively slow, then split it to a separate parameter like regex (boolean) to switch between the two behaviors.

Can you please check if this is what you are referring to.
Thanks
![image](https://user-images.githubusercontent.com/19877300/61064242-09fc9380-a41f-11e9-8047-a41a0b6c4551.png)

Query
```
{
  allDocuments(evidence: "methylation.*mediated") {
    evidence
  }
}
```
GraphQL API [Link](https://reach-api.nrnb-docker.ucsd.edu)

**Comment by cannin** [comment]
This works: 

{
  allDocuments(evidence: "DNA.*[mediated|damage]") {
    evidence
  }
}
