### ISSUE TITLE
Extract MeshHeadingList from Pubmed

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#56]
Similar to #53 also extract MeshHeadingList, these are "topics" represented in the paper and may help users prioritize documents.

**Comment by RohitChattopadhyay** [comment]
The output has been updated with _topics_
[Link to output](https://www.dropbox.com/s/rqthrdqcvt8os0z/pubmed.zip?dl=0)

**Comment by cannin** [comment]
Can you post a subset of the output as a gist?

**Comment by cannin** [comment]
In code, these should always be referred to as mesh_headings

**Comment by RohitChattopadhyay** [comment]
> Can you post a subset of the output as a gist?

[Link to Gist](https://gist.github.com/RohitChattopadhyay/c25cf2ba95e98ee079947529dc77e6ad)
It has the first 100 rows,please let me know if more is required.
Thanks

**Comment by RohitChattopadhyay** [comment]
> [Link to Gist](https://gist.github.com/RohitChattopadhyay/c25cf2ba95e98ee079947529dc77e6ad)
> It has the first 100 rows,please let me know if more is required.

I have added more rows, now total 1000 rows are present in the gist.

**Comment by RohitChattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/19877300/61175425-baf46100-a5cc-11e9-9804-418427a8da6b.png)
MeSH headings and Publication type (#53 ) has been added in API and [deployed](http://reach-api.nrnb-docker.ucsd.edu).
