### ISSUE TITLE
Change the word "Synonyms" to "Matched Entities" in the Details Page

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#57]
Our synonyms are not quite synonyms, so let's change the word to something better like "Matched Entities" or "Matches"

**Comment by RohitChattopadhyay** [comment]
The python package [protmapper](https://github.com/indralab/protmapper/blob/master/protmapper/uniprot_client.py#L354) has some functions to get synonyms, will this help us?

**Comment by cannin** [comment]
We don't have to get synonyms. We should just not label what we have incorrectly.

**Comment by RohitChattopadhyay** [comment]
The change has been deployed
[Build Log](https://docs.google.com/document/d/1K0jum9lJQsEfneMKBJv3Fk-iFEjwwOzLrJRCc_Mzoyg/edit?usp=sharing)
Build Time: 83 minutes, The process has suffered due to the usage of CPU by the data-generation pipeline
