### ISSUE TITLE
Obtain Usage Statistics for GraphQL Queries

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#61]
Is it possible to get statistics on the number of API calls? Potentially, using Google Analytics? I have doubts on depending on Apollo Optics (https://blog.apollographql.com/tagged/apollo-optics) or any small startup with a small service that might disappear.

**Comment by RohitChattopadhyay** [comment]
Google Analytics has [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/), Can you please take a look.
In case we go with this, we will need a proper Google Analytics ID during development and testing. So should I make a temporary dummy Analytics ID using my Google Account?

**Comment by RohitChattopadhyay** [comment]
> Apollo Optics

Apollo Optics is now [Apollo Engine](https://engine.apollographql.com)
The free plan has a data retention of 24hours.

In Google Analytics, we can use the [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/), to get basic details.

**Comment by cannin** [comment]
For now, let's go with Google Analytics.
