### ISSUE TITLE
Provide An Endpoint to Allow Identifier Queries 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#7]
Users should be able to query for identifiers, like: "uniprot:P55851" 

The example query below returns articles for participant_a matches but the query should search participant_a OR participant_b

    curl -i 'http://API_URL/api/v1/articles?where={"extracted_information.participant_a.identifier": "uniprot:P55851"}' 

How can this be done? Is it possible to simplify the query?

**Comment by RohitChattopadhyay** [comment]
I am unable to find a solution for the following problems
1. Flask restricting lookup to sub-document field ( ref https://github.com/pyeve/eve/issues/886 )
2. Display all matches with additional_lookup

As a **way around**, I suggest that we redirect a request like `api/v1/identifiers/uniprot:P55851` to 
`api/v1/articles?where={"$or":[{"extracted_information.participant_a.identifier":"uniprot:P55851"},{"extracted_information.participant_b.identifier":"uniprot:P55851"}]}`
This is a valid solution but involves a redirection. I will continue as per guidance

**Comment by RohitChattopadhyay** [comment]
Posted in StackOverflow asking for a solution, no help till now
https://stackoverflow.com/questions/56219214/nested-additional-lookup

**Comment by cannin** [comment]
The redirect is acceptable for now.
