### ISSUE TITLE
Create and Configure MongoDB Instance with Docker 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#8]
This is related to #5 but different. We will run MongoDB on a server using Docker. 

https://hub.docker.com/_/mongo

The command should look something like this to start things up: 

docker run -d -v /var/lib/mongo:/data/db -v /home/user/mongo.conf:/etc/mongo.conf -p port:port image_name

The command is from: https://stackoverflow.com/questions/37063662/docker-mongodb-config-file

But try it out locally. Make sure the data and the configuration file live outside of the Docker container. Make the necessary conf file; do not commit this file to GitHub. 

Write a Bash script show the commands necessary to start the server, and I will run them.

**Comment by RohitChattopadhyay** [comment]
The GraphQL image and MongoDB image are merged into a single image as they are directly related to each other.
Image in Docker Hub [rchattopadhyay/reach-api](https://hub.docker.com/r/rchattopadhyay/reach-api)
Synced branch for auto-build [RohitChattopadhyay/docker-api](https://github.com/RohitChattopadhyay/ihop-reach/tree/docker-api)

**Comment by RohitChattopadhyay** [comment]
MongDB Indexes can be found [here](https://github.com/RohitChattopadhyay/ihop-reach/blob/15efcfc35f547bf9d1e443480f55535655d72710/src/setup.sh#L35).
