### ISSUE TITLE
Make Project Page for Repository (for Reports)

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#9]
Any reports will be done as part of GitHub as well. Please use gh-pages. Links below:

https://help.github.com/en/articles/user-organization-and-project-pages

http://www.stephaniehicks.com/githubPages_tutorial/pages/orphan-ghpages.html

**Comment by cannin** [comment]
@RohitChattopadhyay the page exists here: 

https://cannin.github.io/ihop-reach/

commit content here: 

https://github.com/cannin/ihop-reach/tree/gh-pages

Close this issue when you read it.

**Comment by RohitChattopadhyay** [comment]
Project Github page setup is done at https://cannin.github.io/ihop-reach/
